### ISSUE TITLE
Configure exchange rates parameters

### ISSUE THREAD

**Issue by arkaitzgarro** [arkaitzgarro/symfony-ecommerce#2]
``` yml
#app/config/config.yml
elcodi_currency:
    open_exchange_rates:
        api_id: 0000
```
